
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "F:/ST/STM32CubeCLT_1.18.0/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:36 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
...
